a=float(input("enter the first number: "))
b=float(input("enter the second number: "))
print("the sum of two numbers is: ",a+b)
print("the difference of two numbers is: ",a-b)
print("the product of two numbers is: ",a*b)
print("the division of two numbers is: ",a/b)